import os
import re
import json
from pathlib import Path
from datetime import datetime

def load_diary(path):

    with open(
        path,
        "r",
        encoding="utf-8"
    ) as f:

        return f.read()

def extract_date(filename):

    match = re.search(
        r"\d{4}-\d{2}-\d{2}",
        filename
    )

    if match:

        return match.group()

    return Path(filename).stem
def extract_keywords(text):

    keywords = []

    patterns = [

        "AutoYouTube",
        "MemoryAI",
        "ThamAI",
        "Dashboard",
        "Winner AI",
        "OpenRouter",
        "Github",
        "Production"

    ]

    for p in patterns:

        if p.lower() in text.lower():

            keywords.append(p)

    return keywords

# ==================================================
# EXTRACT DECISIONS
# ==================================================

def extract_decisions(text):

    results = []

    keywords = [

        "quyết định",

        "freeze",

        "complete",

        "pass",

        "chốt"

    ]

    for line in text.splitlines():

        lower = line.lower()

        if any(k in lower for k in keywords):

            results.append(line.strip())
    results = list(dict.fromkeys(results))
    
    return results


# ==================================================
# EXTRACT LESSONS
# ==================================================

def extract_lessons(text):

    results = []

    keywords = [

        "bài học",

        "lesson",

        "kinh nghiệm"

    ]

    for line in text.splitlines():

        lower = line.lower()

        if any(k in lower for k in keywords):

            results.append(line.strip())

    return results


# ==================================================
# EXTRACT RELATED PROJECTS
# ==================================================

def extract_projects(text):

    projects = []

    names = [

        "AutoYouTube",

        "MemoryAI",

        "ThamAI",

        "TalkingAI"

    ]

    lower = text.lower()

    for name in names:

        if name.lower() in lower:

            projects.append(name)

    return projects

def extract_completed(text):

    completed = []

    for line in text.splitlines():

        line = line.strip()

        if line.startswith("✅"):

            completed.append(

                line.replace("✅", "").strip()

            )

    return completed


def extract_next_tasks(text):

    tasks = []

    collecting = False

    for line in text.splitlines():

        if "Kế hoạch" in line \
        or "Việc cần làm" in line:

            collecting = True

            continue

        if collecting:

            if not line.strip():

                break

            tasks.append(line.strip())

    return tasks

def save_summary(
    diary_path,
    completed,
    decisions,
    lessons,
    keywords,
    tasks,
    projects
):

    summary_dir = Path(
        r"D:\MemoryAI\11_Diary_Summary\summaries"
    )

    summary_dir.mkdir(
        parents=True,
        exist_ok=True
    )

    name = extract_date(
        Path(diary_path).name
    )

    created = datetime.now().strftime(
        "%Y-%m-%d"
    )

    version = "BUILD-20.3"

    outfile = summary_dir / (
        name + "_summary.md"
    )

    lines = []

    lines.append("# Diary Summary\n\n")
    summary_id = f"DS-{name}"

    generated_by = "Diary Processor BUILD-20.3"
    lines.append(
        f"ID: {summary_id}\n"
    )

    lines.append(
        f"Date: {name}\n"
    )

    lines.append(
        f"Created: {created}\n"
    )

    lines.append(
        f"Version: {version}\n"
    )

    lines.append(
        f"Generated By: {generated_by}\n"
    )

    lines.append(
        f"Source: {Path(diary_path).name}\n"
    )
    # ===========================
    # Completed
    # ===========================

    lines.append("\n## Completed\n")

    if completed:

        for item in completed:

            lines.append(f"- {item}\n")

    else:

        lines.append("- Không có\n")

    # ===========================
    # Decisions
    # ===========================

    lines.append("\n## Decisions\n")

    if decisions:

        for item in decisions:

            lines.append(f"- {item}\n")

    else:

        lines.append("- Không có\n")

    # ===========================
    # Lessons
    # ===========================

    lines.append("\n## Lessons\n")

    if lessons:

        for item in lessons:

            lines.append(f"- {item}\n")

    else:

        lines.append("- Không có\n")

    # ===========================
    # Keywords
    # ===========================

    lines.append("\n## Keywords\n")

    if keywords:

        for item in keywords:

            lines.append(f"- {item}\n")

    else:

        lines.append("- Không có\n")

    # ===========================
    # Next Tasks
    # ===========================

    lines.append("\n## Next Tasks\n")

    if tasks:

        for item in tasks:

            lines.append(f"- {item}\n")

    else:

        lines.append("- Không có\n")

    # ===========================
    # Related Projects
    # ===========================

    lines.append("\n## Related Projects\n")

    if projects:

        for item in projects:

            lines.append(f"- {item}\n")

    else:

        lines.append("- Không có\n")

    # ======================
    # Ghi file
    # ======================

    with open(
        outfile,
        "w",
        encoding="utf-8"
    ) as f:

        f.writelines(lines)

    print()

    print("✅ Summary saved:")

    print(outfile)

    update_summary_index(

        summary_id,

        name,

        Path(diary_path).name,

        keywords,

        projects,

        version
    )

def update_summary_index(
    summary_id,
    date,
    source,
    keywords,
    projects,
    version
):

    index_file = Path(
        r"D:\MemoryAI\11_Diary_Summary\summary_index.json"
    )

    if index_file.exists():

        with open(
            index_file,
            "r",
            encoding="utf-8"
        ) as f:

            try:

                data = json.load(f)

            except:

                data = []

    else:

        data = []

    # Xóa bản cũ nếu đã có

    data = [

        item

        for item in data

        if item["id"] != summary_id

    ]

    # Thêm bản mới

    data.append({

        "id": summary_id,

        "date": date,

        "source": source,

        "version": version,

        "projects": projects,

        "keywords": keywords

    })

    # Sắp xếp theo ngày

    data.sort(

        key=lambda x: x["date"]

    )

    with open(

        index_file,

        "w",

        encoding="utf-8"

    ) as f:

        json.dump(

            data,

            f,

            indent=4,

            ensure_ascii=False

        )

def main():

    diary = input(
        "Đường dẫn nhật ký: "
    ).strip()

    if not os.path.exists(diary):

        print("Không tìm thấy file.")

        return

    text = load_diary(diary)

    print()

    print("=" * 70)
    print("DIARY SUMMARY")
    print("=" * 70)

    print()

    print("Completed")

    print("-" * 30)

    completed = extract_completed(text)

    if completed:

        for item in completed:

            print("✔", item)

    else:

        print("Không có.")

    print()

    print("Keywords")

    print("-" * 30)

    keywords = extract_keywords(text)

    if keywords:

        for k in keywords:

            print("-", k)

    else:

        print("Không có.")

    print()

    print("Next Tasks")

    print("-" * 30)

    tasks = extract_next_tasks(text)

    if tasks:

        for t in tasks:

            print("-", t)

    else:

        print("Không có.")

    decisions = extract_decisions(text)

    lessons = extract_lessons(text)

    projects = extract_projects(text)

    save_summary(

        diary,

        completed,

        decisions,

        lessons,

        keywords,

        tasks,

        projects

    )
if __name__ == "__main__":

    main()